{
 "title": "Suivi de la Charge Énergétique en Temps Réel Copy",
 "time": { "from": "2016-02-19T23:00:00.000Z", "to": "2016-02-29T23:00:00.000Z" },
 "panels": [
  {
   "title": "Charge Actuelle (kW)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "energy_db",
     "rawSql": "SELECT power_kw \r\nFROM energy_data \r\nWHERE $__timeFilter(time) \r\nORDER BY time DESC \r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Indicateurs de Performance de Consommation",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "dataset": "energy_db",
     "rawSql": "SELECT \r\n    region, \r\n    date_trunc('hour', time) AS \"Heure\", \r\n    round(avg(power_kw)::numeric, 2) AS \"Moyenne (kW)\"\r\nFROM energy_data \r\nGROUP BY 1, 2 \r\nORDER BY 2 DESC \r\nLIMIT 10;"
    },
    {
     "dataset": "energy_db",
     "rawSql": "SELECT max(power_kw) FROM energy_data WHERE $__timeFilter(time)"
    }
   ]
  },
  {
   "title": "Analyse Comparative : Consommation Moyenne par Jour",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "dataset": "energy_db",
     "rawSql": "SELECT \r\n    date_trunc('day', time) AS \"Jour\", \r\n    avg(power_kw) AS \"Moyenne\"\r\nFROM energy_data \r\nWHERE $__timeFilter(time)\r\nGROUP BY 1 \r\nORDER BY 1 ASC;"
    }
   ]
  },
  {
   "title": "Suivi de la Charge Énergétique en Temps Réel",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 14 },
   "targets": [
    {
     "dataset": "energy_db",
     "rawSql": "SELECT\r\n  $__timeGroupAlias(time, 1h),\r\n  avg(power_kw) AS \"Consommation Moyenne (kW)\"\r\nFROM energy_data\r\nWHERE\r\n  $__timeFilter(time) AND region = 'DE'\r\nGROUP BY 1\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Table analytique",
   "type": "table",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 14 },
   "targets": [
    {
     "dataset": "energy_db",
     "rawSql": "SELECT \r\n    region, \r\n    date_trunc('hour', time) AS \"Heure\", \r\n    round(avg(power_kw)::numeric, 2) AS \"Moyenne (kW)\"\r\nFROM energy_data \r\nWHERE $__timeFilter(time)\r\nGROUP BY 1, 2 \r\nORDER BY 2 DESC \r\nLIMIT 10;"
    },
    {
     "dataset": "energy_db",
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  }
 ]
}